In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 578.0 MB 17 kB/s 
     |████████████████████████████████| 1.7 MB 46.0 MB/s 
     |████████████████████████████████| 5.9 MB 54.0 MB/s 
     |████████████████████████████████| 438 kB 66.9 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.5

In [2]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'I would like to travel']


In [10]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'I would like to travel']

In [16]:
#Vocabulary size
voc_size=500

In [17]:
one_hot_resp=[one_hot(words,voc_size) for words in sent]
one_hot_resp


[[92, 428, 90, 197],
 [92, 428, 90, 486],
 [92, 319, 90, 305],
 [221, 338, 90, 225, 19],
 [221, 338, 90, 225, 314],
 [230, 92, 457, 90, 40],
 [221, 340, 422, 463, 470]]

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [22]:
sent_length=8
embedded_docs=pad_sequences(one_hot_resp,padding='pre',maxlen=sent_length)
embedded_docs

array([[  0,   0,   0,   0,  92, 428,  90, 197],
       [  0,   0,   0,   0,  92, 428,  90, 486],
       [  0,   0,   0,   0,  92, 319,  90, 305],
       [  0,   0,   0, 221, 338,  90, 225,  19],
       [  0,   0,   0, 221, 338,  90, 225, 314],
       [  0,   0,   0, 230,  92, 457,  90,  40],
       [  0,   0,   0, 221, 340, 422, 463, 470]], dtype=int32)

In [23]:
dim=10 #feature dimension
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [24]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [25]:
embedded_docs[0]

array([  0,   0,   0,   0,  92, 428,  90, 197], dtype=int32)

In [27]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 37ms/step


array([[[ 0.00958731,  0.04644531, -0.02453365, -0.01197983,
         -0.01943681, -0.01337557, -0.02905227,  0.03527069,
          0.02606089, -0.03475746],
        [ 0.00958731,  0.04644531, -0.02453365, -0.01197983,
         -0.01943681, -0.01337557, -0.02905227,  0.03527069,
          0.02606089, -0.03475746],
        [ 0.00958731,  0.04644531, -0.02453365, -0.01197983,
         -0.01943681, -0.01337557, -0.02905227,  0.03527069,
          0.02606089, -0.03475746],
        [ 0.00958731,  0.04644531, -0.02453365, -0.01197983,
         -0.01943681, -0.01337557, -0.02905227,  0.03527069,
          0.02606089, -0.03475746],
        [-0.03752562, -0.024798  ,  0.02229167, -0.00440447,
         -0.0483802 ,  0.03469815,  0.01046206,  0.00843231,
          0.02959465, -0.04316049],
        [-0.04650366,  0.04639946,  0.00962315, -0.03049424,
          0.00446049, -0.02921594, -0.04809252, -0.00112071,
         -0.02730267, -0.01272328],
        [-0.04047086, -0.00699223,  0.01620502, -0.0